//Class containing reference for how each possible book name converts to an hid code.
const idNames = {
    "DEMO":"DEM",
    //Books
    "THE VOICE OF AFRICA":"VOA",
    "THE VOICE OF AFRICA V.1":"VOA",
    "THE VOICE OF AFRICA V.2":"VOA",
    "THE VOICE OF AFRICA V.3":"VOA",
    "THE VOICE OF AFRICA V.4":"VOA",
    "UND AFRIKA SPRACH V.1":"VOA",
    "UND AFRIKA SPRACH V.2":"VOA",
    "UND AFRIKA SPRACH V.3":"VOA",
    //Travelogues
    "VOYAGE EN ABYSSINIE":"VEA",
    "THROUGH THE DARK CONTINENT":"TDC",
    "SEVENTEEN YEARS IN THE YORUBA COUNTRY":"SYC",
    "VOYAGES, ADVENTURES ET CAPTIVITÉ DE J. BONNAT CHEZ LES ACHANTIS":"VJA",
    //Artbooks [MUST ONLY INCLUDE OR PRIMARILY CENTER PIECES OF ART; SKETHCES, PAINTINGS]
    "AFRICAN SCENERY AND ANIMALS":"ASA",
    "SKETCHES REPRESENTING THE NATIVE TRIBES ANIMALS AND SCENERY OF SOUTHERN AFRICA":"SRS",
    //Scientific Catalogue [AS IN, BOOKS FOCUSED ON TRACKING, ORGANIZING, AND ARRANGING THINGS]

    //Anthropological, Ethnographic & Archaeological
    "PIONEERS IN WEST AFRICA":"PWA",
    "LAND AND PEOPLES OF THE KASAI":"LAK",
    "NOTES ETHNOGRAPHIQUES SUR LES PEUPLES COMMUNÉMENT APPELES BAKUBA":"NEB",
    //Regional Surveys & Area Studies
    "THE NATURAL HISTORY OF MAN":"TNH",
    "ILLUSTRATED HOME BOOK OF THE WORLDS GREAT NATIONS":"IGN",
    "LE FRANCE AU DAHOMEY":"FAD",
    //World/Continental-Surveys [AS IN, BOOKS AIMING TO GIVE KNOWLEDGE ON CONTINENTAL-SCOPE REGIONS OR EARTH AS A WHOLE]
    //
    //Publications
    //Newspapers
    "ILLUSTRATED LONDON NEWS":"ILN",
    "THE GRAPHIC":"TG",
    "THEGRAPHIC":"TG",
    "A QUARTERLY TOKEN":"AQS",
    "TOUR DU MONDE":"TDM",
    "LE PETITE JOURNAL":"LPJ",
    //Magazines
    //Journal Articles [AS IN, ARTICLES WRITTEN IN NON-ACADEMIC JOURNALS]
    //Journal Articles [AS IN, ARTICLES WRITTEN IN ACADEMIC JOURNALS]
    "THE ARCHITECTURAL REVIEW":"JAR"

    

}
module.exports = idNames;